### ISSUE TITLE
Package not found by npm nor yarn

### ISSUE THREAD

**Issue by mateusbds** [GemunIon/nestjs-sqs#32]
Package cannot be found by any package manager

Yarn:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/@gemunion%2fnestjs-sqs: Not found".
```

Npm
```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@gemunion%2fnestjs-sqs - Not found
```

**Comment by TrejGun** [comment]
Hi man!
Thanks for checking it out

The package is definitely there https://github.com/GemunIon/nestjs-sqs/packages/940625
it looks like you have to adjust your .npmrc to read

```
@gemunion:registry=https://npm.pkg.github.com/
```

**Comment by GuilhermeCunha** [comment]
I'm having the same error

![image](https://user-images.githubusercontent.com/19752833/133372032-77666cd0-e127-43c6-b47a-c12815cfff6a.png)

**Comment by TrejGun** [comment]
ok ok I just published it on npmjs.com

https://www.npmjs.com/package/@gemunion/nestjs-sqs

**Comment by mateusbds** [comment]
Thanks!
