### ISSUE TITLE
Support in standart queue + delaySeconds + hard coded groupId

### ISSUE THREAD

**Issue by meifif** [GemunIon/nestjs-sqs#83]
in your file @gemunion/nestjs-sqs/dist/sqs.serializer.js you have the next code:

`class SqsSerializer {
    serialize(value) {
        const id = (0, uuid_1.v4)();
        return {
            id,
            body: JSON.stringify(value),
            delaySeconds: 0,
            groupId: "test",
            deduplicationId: id,
        };
    }
}`

as you can see the groupId is hardcoded

MessageDeduplicationId and MessageGroupId cannot be used in a Standard Queue, according to the [SQS reference](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SendMessage.html) - so when using a standard code we received
` 'InvalidParameterValue', 'Message': 'The request include parameter that is not valid for this queue type'`

and the delay seconds should be in the config on the SqsServer I will try to add that support for all SQS configs so you can use them for the rest of the code

**Comment by TrejGun** [comment]
thanks for trying my lib!

for now, you can extend the current serializer and pass it as an option, and I would gladly accept PR with a better solution

**Comment by TrejGun** [comment]
I'm going to close this, for now, feel free to reopen
